# Site settings
title: Paul's Blog
SEOTitle: Paul Blog
header-img: img/home-bg-test.jpg
email: Jepson.xu@gmail.com
description: "Make data valuable | machine learning, 数据创造价值 | 这里是Paul的个人博客，与你一起发现更大的世界。"
keyword: "AI, Machine learning, Algorithm, data analytics"
url: "https://jerpson.github.io"              # your host, for absolute URL
#baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     
#zhihu_username:     username
github_username:    jerpson
#twitter_username:   username
#facebook_username:  username
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: Jerpson

# Netease settings
#netease_comment: true


comments:
  disqus: false
  
  
  gitalk: true
  gitalk_clientID: '15e7283866176900b1ce'
  gitalk_Secret: 'bdc611d37fee4838e37e6445dc9dcbd4572f8aa4'
  gitalk_repo: 'jerpson.github.io'
  gitalk_owner: 'jerpson'
  gitalk_admin: 'jerpson'
  distractionFreeMode: true
  

# Analytics settings
# Baidu Analytics 
ba_track_id: baf75e05c222704d34f7ff5488ebe868

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>看得更远是因为站在巨人的肩膀上"
sidebar-avatar: /img/ever_self.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true                   # 由于经常写公式，因此在原作者的false修改为true了



# Friends
friends: [
    {
        title: "deeplearning.ai",
        href: "https://www.deeplearning.ai/"
    },{
        title: "landing.ai",
        href: "https://landing.ai/"
    }
]
